name: Deploy backend to production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build backend artifact
    environment: Production
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          lfs: false
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: Build backend
        run: dotnet publish -c Release -r linux-arm64 --self-contained false src/Costasdev.Busurbano.Backend/Costasdev.Busurbano.Backend.csproj -o dist/backend
      - name: Archive Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: dist/backend
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy backend to production server
    environment: Production
    permissions:
      contents: read
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: backend
          path: dist/backend
      - name: Connect to tailnet
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:ci
      - name: Wait for reachability
        run: |
          until tailscale ping ${{ secrets.TARGET_HOST }}; do
            echo "Waiting for Tailscale to connect..."
            sleep 2
          done
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.TARGET_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy backend
        run: |
          ssh ${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }} "sudo systemctl stop busurbano"
          scp -r dist/backend/* ${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }}:/opt/ventasync/
          ssh ${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }} "sudo systemctl start busurbano"
